name: test-chart

on:
  push:
    branches:
      - dev

jobs:
  test-chart:
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.HELM_IMAGE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all history for all branches and tags
      - name: Render Chart
        run: |
          helm template --debug --release-name popeye -f ./.test/values.yaml  --output-dir ./.test/result ./
      - name: Diff Folders
        run: |
          diff -rq ./.test/expected ./.test/result
