---
# Source: popeye/templates/rbac/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: popeye-sa
  labels:
    app.kubernetes.io/version: "v0.22.1"
    app.kubernetes.io/managed-by: Helm
